// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | "/"
    | "/_locales/en/messages.json"
    | "/background.js"
    | "/content-scripts/01-auth.js"
    | "/content-scripts/02-inject.js"
    | "/content-scripts/03-socket.js"
    | "/content-scripts/04-main.js"
    | "/content-scripts/05-callback.js"
    | "/images/icon-128.png"
    | "/images/icon-16.png"
    | "/images/icon-32.png"
    | "/images/icon-48.png"
    | "/popup.html"
    | "/rules.json"
    | "/scripts/compat.js"
    | "/scripts/main.js"
    | "/scripts/socket.io.min.js"
    | "/scripts/style.css"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
